### ISSUE TITLE
개발과 관련하여 고민해야 할 사항은 여기에 올려주세요!

### ISSUE THREAD

**Issue by zoeyoon** [oss-miniproject/miniproject#3]

**Comment by seongju1015** [comment]
selectMenu에 관하여
 처음 프로그램 시작을 하였을 때 selectMenu(1)로 관리자 모드와 회원 모드 구분 - 여기서 관리자 모드는 비밀번호가 일치하지 않으면, 회원모드는 회원 아이디가 일치하지 않으면 에러 메세지 출력 후 break. 아이디나 비밀번호 확인은 문자열 비교로 구현.
 관리자 모드로 들어갔을 때  selectMenu(2)에는 맨 위에 '관리자 모드입니다.' 라는 메세지 추가.
 회원 모드로 들어갔을 때  selectMenu(3)에는 맨 위에 '회원 모드입니다.' 라는 메세지 추가.

**Comment by seongju1015** [comment]
main에 대하여
처음 while 반복문 안에서 selectMenu(1)로 관리자 모드와 회원 모드 구분
그 후에 if문을 이용하여 그 안에 while문을 따로 추가.
즉 총 while문이 처음 입장(모드 선택), 관리자모드, 사용자모드 이렇게 3개 들어가야하는 것이 맞을까요?

**Comment by zoeyoon** [comment]
> main에 대하여 처음 while 반복문 안에서 selectMenu(1)로 관리자 모드와 회원 모드 구분 그 후에 if문을 이용하여 그 안에 while문을 따로 추가. 즉 총 while문이 처음 입장(모드 선택), 관리자모드, 사용자모드 이렇게 3개 들어가야하는 것이 맞을까요?

네! 우선은 그렇게 구현하는 것으로 방향을 잡아두고
추후 개발 과정에서 프로그램 흐름이 더 자연스러운 방식이 있다면 해당 방식으로 채택해서 구현하면 좋을거 같아요 !

**Comment by zoeyoon** [comment]
관리자 모드와 사용자 모드를 구분하여 개발하기 위해 각 모드에 대한 c파일을 나누어서 작성하는 것이 좋을까요? 아님 지금처럼 하나로 유지하여 작성하는 것이 좋을까요?

**Comment by seongju1015** [comment]
어짜피 main에서 관리자모드일 때와 사용자모드일 때를  if문을 이용해서 구분하는 것이니, 하나로 유지하여 작성해도 문제는 없어보입니다. 둘 다 상관없을 듯 하니, 좀 더 편하게 작업할 수 있는 걸로 하는 게 어떤가요? 저는 둘 다 상관없습니다.

**Comment by zoeyoon** [comment]
> 어짜피 main에서 관리자모드일 때와 사용자모드일 때를 if문을 이용해서 구분하는 것이니, 하나로 유지하여 작성해도 문제는 없어보입니다. 둘 다 상관없을 듯 하니, 좀 더 편하게 작업할 수 있는 걸로 하는 게 어떤가요? 저는 둘 다 상관없습니다.

그럼 우선 한 파일에 다 작성 하고 문제 없이 프로그램이 돌아간다면 추후에 나누는 방식으로 진행해도 될거 같아요!

**Comment by zoeyoon** [comment]
파일 저장의 경우 두가지 모드에서 다 지원을 해야할지, saveData함수가 프로그램이 종료될 수 있는 시점마다 실행 될 수 있게 하는 것을 통해 상태를 저장할 수 있게 할지 고민입니다! 제가 생각하기엔 후자의 방식이 더 좋으리라 생각되는데 어떻게 생각하시는지 알려주세요! :D

**Comment by seongju1015** [comment]
오 후자의 방식은 생각을 못해봤는데 참신하고 효율적이네요 ! 후자 방식으로 채택하는 것이 좋아보이네요. 메뉴 목록에서 저장 기능을 제외해버리고, '종료'  기능을 '종료 및 저장' 기능으로 이름을 바꾸고, saveData 와 break를 넣는 방식으로 수정할게요.
