### ISSUE TITLE
[TEAM PROJECT#1] 프로젝트 기획 및 설계

### ISSUE THREAD

**Issue by zoeyoon** [oss-miniproject/miniproject#4]
2023.05.01 meeting

[주제]
헬스장 회원 관리 프로그램

[대략적인 프로그램 흐름]
관리자모드와 회원모드를 구분하여 구현

[역할 분담]
이성주: 관리자 모드 구현
윤소예: 회원 모드 구현

[해야할 것]
구조체 정의
필요한 함수 정의

**Comment by seongju1015** [comment]
프로그램 이름을 HGMP로 하면 한동에 있는 헬스장을 관리하는 프로그램 같은 느낌이 들어요. 혹시 그냥 GMP(Gym Management Program)으로 바꾸는 것은 어떨까요?

**Comment by zoeyoon** [comment]
> 프로그램 이름을 HGMP로 하면 한동에 있는 헬스장을 관리하는 프로그램 같은 느낌이 들어요. 혹시 그냥 GMP(Gym Management Program)으로 바꾸는 것은 어떨까요?

그렇게 생각될수도 있겠네요!
프로그램 이름을 GMP로 바꾸는거 좋은 아이디어 같아요! :D
