### ISSUE TITLE
about 구조체 User

### ISSUE THREAD

**Issue by seongju1015** [oss-miniproject/miniproject#5]
구조체 User에 관해서 구성할 때 배열로 넣으려면, 첫 번째에 필라테스, 두 번째에 pt, 마지막에 헬스가 들어가야하는데, 이걸 문자열로 배열에 넣는 깔끔한 방법이 고민입니다. 
char class_name[20] 문자열 따로
int class_list[3] 따로 이렇게 해서
만약 class_list[0]이면 class_name = '필라테스' <- 이런 방법도 있는데, 이렇게 하면 한번에 수업을 하나씩만 신청할 수 있게 됩니다.
생각해본 해결방법으로는, 한번에 수업을 하나씩만 듣게 하거나 또는 c++ string을 이용하는 것, 그리고 수업 목록 자체가 작으니, 일일이 배열 몇번부터 몇번까지가 필라테스인지 헬스인지 구분해서 기록하는 방법도 있는 것 같습니다.
같이 고민해봐요 :)

**Comment by zoeyoon** [comment]
> 구조체 User에 관해서 구성할 때 배열로 넣으려면, 첫 번째에 필라테스, 두 번째에 pt, 마지막에 헬스가 들어가야하는데, 이걸 문자열로 배열에 넣는 깔끔한 방법이 고민입니다. char class_name[20] 문자열 따로 int class_list[3] 따로 이렇게 해서 만약 class_list[0]이면 class_name = '필라테스' <- 이런 방법도 있는데, 이렇게 하면 한번에 수업을 하나씩만 신청할 수 있게 됩니다. 생각해본 해결방법으로는, 한번에 수업을 하나씩만 듣게 하거나 또는 c++ string을 이용하는 것, 그리고 수업 목록 자체가 작으니, 일일이 배열 몇번부터 몇번까지가 필라테스인지 헬스인지 구분해서 기록하는 방법도 있는 것 같습니다. 같이 고민해봐요 :)

네! 해당 내용에 대해서 고민해보겠습니다 ! :)

**Comment by seongju1015** [comment]
생각을 해봤는데 크게 2가지로 추릴 수 있을 것 같아요.
1. 문자열로 받아서 한번에 한개의 수업만 들을 수 있게 한다. (하지만, 유저모드- 수업 신청 함수에서는 printf로 pt를 신청하면 헬스는 기본으로 제공된다는 메세지를 출력)
2. 공백 포함 문자열로 받아서 여러개의 수업(예를들면 필라테스와 pt)를 같이 신청할 수 있게한다.

**Comment by zoeyoon** [comment]
> 생각을 해봤는데 크게 2가지로 추릴 수 있을 것 같아요.
> 
> 1. 문자열로 받아서 한번에 한개의 수업만 들을 수 있게 한다. (하지만, 유저모드- 수업 신청 함수에서는 printf로 pt를 신청하면 헬스는 기본으로 제공된다는 메세지를 출력)
> 2. 공백 포함 문자열로 받아서 여러개의 수업(예를들면 필라테스와 pt)를 같이 신청할 수 있게한다.

2번 방식의 경우 이미 수강하고 있는 수업에 대한 판별이 어려워 질거 같아요..

기존에 생각한 방식대로 수강여부를 저장해두는 정수형 배열을 하나 만들어두고 회원 정보를 출력해줄 때 조건문을 사용하여 수강 여부가 1인 수업에 대해서 출력을 하게끔 구현하는 방식은 어떨까요?

**Comment by zoeyoon** [comment]
**구조체 내에 정수배열 선언:**
```
typedef struct{
    char name[20];
    char ID[20];
    int classList[3] = {0, 0, 0}; //초기 값 모두 0으로 선언
    int day;
} User;
```
회원정보 출력 함수
```
char classOffered[3][30] = {'필라테스', '헬스', 'PT'};
printf("이름: %c 수강수업 : " , u->name);
for (int i=0; i<3; i++) {
   if (u->classList[i] == 1) {
      printf("%s ", classOffered[i]);
   }
}
printf("잔여일: %d\n", u->coverage);
```

이런 식의 구현 방식은 어떨까요?

**Comment by seongju1015** [comment]
오 좋은 것 같습니다. 문제 없어 보이네요 :) 일단 추가하고 혹시라도 오류가 발생하면 수정해나가는 방식으로 해봐요.

**Comment by seongju1015** [comment]
위 구현방법 좋은 것 같습니다. 다만, 우리 프로그램을 모르는 사람이 사용할 경우, 만약 회원 정보를 입력할 때 수강중인 수업을 물어보면 int타입이 아니라 문자열형식으로 입력할 것 같아요. 
Printf 구문을 사용하여서 숫자로 입력하라고 알려주는 게 좋을 것 같아요 ex) 숫자로 입력하시오 (0. 필라테스 / 1. pt / 2. 헬스) 이런식으로 어떨까요?
 그리고 scanf 받을 때도 if를 활용해서 아스키 코드값 0~2이 아니면 오류를 출력하고 return 0을하는 식으로 구현하면 좋을 것 같습니다.
이에 대해서 의견 주시면 제가 내용 수정해서 추가할게요 :)

**Comment by zoeyoon** [comment]
> 위 구현방법 좋은 것 같습니다. 다만, 우리 프로그램을 모르는 사람이 사용할 경우, 만약 회원 정보를 입력할 때 수강중인 수업을 물어보면 int타입이 아니라 문자열형식으로 입력할 것 같아요. Printf 구문을 사용하여서 숫자로 입력하라고 알려주는 게 좋을 것 같아요 ex) 숫자로 입력하시오 (0. 필라테스 / 1. pt / 2. 헬스) 이런식으로 어떨까요? 그리고 scanf 받을 때도 if를 활용해서 아스키 코드값 0~2이 아니면 오류를 출력하고 return 0을하는 식으로 구현하면 좋을 것 같습니다. 이에 대해서 의견 주시면 제가 내용 수정해서 추가할게요 :)

좋은 아이디어 같아요!! 말 해주신 방식으로 구현하면 될거 같습니다 :-)
